version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
    # Check for updates to GitHub Actions every week
      interval: "weekly"

    # Check for Python dependency updates
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dependencies"
