variable "name" {}
variable "project" {}
variable "region" {}
variable "secret_resource_id" {}
variable "secret_version_name" {}
variable "bucket_name" {}
variable "ingress_settings" {}
variable "runtime" {}
variable "timeout" {}
variable "pubsub_topic" {}
variable "service_account_email" {}
variable "slack_channel" {}
variable "slack_emoji" {}
variable "slack_username" {}
