variable "project" {}
variable "region" {}
variable "name" {}
variable "bucket_name" {}
variable "functions" {}
variable "ingress_settings" {}
variable "runtime" {}
variable "timeout" {}
variable "pubsub_topic" {}
variable "service_account_email" {}
variable "slack_channels" {}
variable "slack_webhook_urls" {}
variable "slack_emoji" {}
variable "slack_username" {}
