version: 2.1

aliases:
  - &branch-filter
    branches:
      only:
        - dev
        - main

jobs:
  python_tests:
    working_directory: /tmp/project
    docker:
      - image: python:3.9
    steps:
      - checkout
      - run:
          name: install dependencies
          command: pip install -r requirements-dev.txt
      - run:
          name: black on manual scans
          command: black --check --line-length 120 .
      - run:
          name: prospector on manual scans
          command: prospector --max-line-length 120 --profile tests/prospector/profile.yaml
  terraform_format:
    working_directory: /tmp/project
    docker:
      - image: hashicorp/terraform:1.0.11
    steps:
      - checkout
      - run:
          name: terraform format
          command: terraform fmt -check -recursive
  plan:
    working_directory: /tmp/project
    docker:
      - image: hashicorp/terraform:1.0.11
    steps:
      - checkout
      - run:
          name: set Google Cloud credentials
          command: 
            echo $GOOGLE_CLOUD_KEYFILE_JSON > google_cloud_keyfile.json
      - run:
          name: terraform state bucket variables
          command: |
            echo "export TERRAFORM_STATE_BUCKET=$TERRAFORM_STATE_BUCKET" >> $BASH_ENV
            echo "export TERRAFORM_STATE_PREFIX=$TERRAFORM_STATE_PREFIX" >> $BASH_ENV
      - run:
          name: terraform init
          command: "set -x;terraform init -backend-config=bucket=$TERRAFORM_STATE_BUCKET -backend-config=prefix=$TERRAFORM_STATE_PREFIX"
      - run:
          name: set terraform workspace
          command: |
            if [ "$CIRCLE_BRANCH" = "main" ]; then
              terraform workspace select prd || terraform workspace new prd
            else
              terraform workspace select "$CIRCLE_BRANCH" || terraform workspace new "$CIRCLE_BRANCH"
            fi
      - run:
          name: terraform plan
          command: terraform plan -out tfplan
      - persist_to_workspace:
          root: .
          paths:
            - .
  apply:
    docker:
      - image: hashicorp/terraform:1.0.11
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform apply
          command: terraform apply -auto-approve tfplan
      - persist_to_workspace:
          root: .
          paths:
            - .

workflows:
  cd:
    jobs:
      - python_tests
      - terraform_format
      - plan:
          filters: *branch-filter
          requires:
            - python_tests
            - terraform_format
      - approve:
          filters: *branch-filter
          type: approval
          requires:
            - plan
      - apply:
          filters: *branch-filter
          requires:
            - approve