name: Tests
on:
  push:

jobs:
  python_tests:
    name: Python tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up Python 3.14
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: '3.14'

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt

      - name: Black
        run: |
          black --check --line-length 120 .

      - name: Prospector
        run: |
          prospector

      - name: install bandit
        run: |
          pip3 install --upgrade bandit
          echo $PATH
          bandit --version
          which bandit

      - name: prepare reports dir
        run: mkdir --parents ${{runner.temp}}/reports_sast_python/

      - name: generate json report
        run: >
          bandit -r
          --exit-zero
          --ini .config/sast_python_bandit_json.yml .
          1> ${{runner.temp}}/reports_sast_python/${RANDOM}.json

      - name: save json report
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: sast_python
          if-no-files-found: error
          path: ${{runner.temp}}/reports_sast_python/

      - name: test code
        run: >
          bandit
          --ini .config/sast_python_bandit_cli.yml .
  
  terraform_tests:
    name: Terraform tests
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: write
      checks: write
    steps:
      - name: Terraform setup
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
        with:
          terraform_version: 1.12.2

      - name: checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Terraform validate
        id: fmt
        run: terraform fmt -check -recursive

      - name: install checkov
        run: |
          pip3 install --upgrade checkov
          echo $PATH
          checkov --version
          which checkov

      - name: prepare reports dir
        run: mkdir --parents ${{runner.temp}}/reports_sast_terraform/

      - name: generate json report
        run: >
          checkov
          --config-file .config/sast_terraform_checkov_json.yml
          --directory .
          1> ${{runner.temp}}/reports_sast_terraform/${RANDOM}.json

      - name: save json report
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: sast_terraform
          if-no-files-found: error
          path: ${{runner.temp}}/reports_sast_terraform/

      - name: test code
        run: >
          checkov
          --config-file .config/sast_terraform_checkov_cli.yml
          --directory .
          
  CodeQL-Build:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'python' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Initialize CodeQL
        uses: github/codeql-action/init@54f647b7e1bb85c95cddabcd46b0c578ec92bc1a # v4.36.3
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@54f647b7e1bb85c95cddabcd46b0c578ec92bc1a # v4.36.3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@54f647b7e1bb85c95cddabcd46b0c578ec92bc1a # v4.36.3
        with:
          category: "/language:${{matrix.language}}"
